/**
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientAppSchema { 
    updated_at?: string;
    name?: string;
    deleted?: boolean;
    contract?: string;
    labels?: object | null;
    id: string;
    token?: string;
    created_at?: string;
    url?: string;
    billing_id?: string;
}

