/**
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PolicyChannelSchema { 
    /**
     * Client uuid. This is the id defined by client app
     */
    client_uuid: string;
    /**
     * Policy Channel config
     */
    config: object;
    created_at?: string;
    /**
     * Policy Channel deleted flag
     */
    deleted: boolean;
    /**
     * Policy Channel enabled flag
     */
    enabled: boolean;
    /**
     * Id
     */
    id: string;
    last_notification?: string | null;
    /**
     * Policy Channel name
     */
    name: string;
    /**
     * Policy Channel type
     */
    type: string;
    updated_at?: string;
}

